### ISSUE TITLE
Arithmetic overflow error converting numeric to data type numeric

### ISSUE THREAD

**Issue by AGlennDa** [trimble-oss/dba-dash#1182]
I'm having an issue with the IdentityColumns collection. 

This is on a SQL Server 2017 Standard RTM CU17. And is only seen on this specific server. 

ErrorContext: 
Collect

Source: IdentityColumn

Microsoft.Data.SqlClient.SqlException (0x80131904): Arithmetic overflow error converting numeric to data type numeric.
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at DBADash.DBCollector.GetDT(String tableName, String SQL, Int32 commandTimeout, SqlParameter[] param) in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 1331
   at DBADash.DBCollector.AddDT(String tableName, String sql, Int32 commandTimeout, SqlParameter[] param) in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 1340
   at DBADash.DBCollector.ExecuteCollection(CollectionType collectionType) in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 1039
   at DBADash.DBCollector.<>c__DisplayClass73_0.<Collect>b__0(Context _) in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 593
   at Polly.Policy.<>c__DisplayClass138_0.<Implementation>b__0(Context ctx, CancellationToken token)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, CancellationToken cancellationToken, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Implementation(Action`2 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute(Action`2 action, Context context, CancellationToken cancellationToken)
   at DBADash.DBCollector.Collect(CollectionType collectionType) in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 589
ClientConnectionId:9d275931-d791-4a16-b159-99097a915d2c
Error Number:8115,State:1,Class:16

**Comment by AGlennDa** [comment]
Thanks. 
I narrowed it down to a specific database with a ident column of BIGINT. 
But the table is empty. I don't see any conditions for taking care of empty tables? 

I added this to the script with a "AND IC.last_value IS NOT NULL"-condition. 
I changed the calculation to take into account to not do the calculations if the table is empty. 
And then in the end i added "AND IC.last_value IS NOT NULL" to filter out any empty tables. 
I don't see any reason to return the empty tables? But I might be wrong on this one. 


`DECLARE @IdentityCollectionThreshold INT = 5
SET NOCOUNT ON
SET TRAN ISOLATION LEVEL READ UNCOMMITTED

DECLARE @DBName SYSNAME
DECLARE @IdentSQL NVARCHAR(MAX)
DECLARE @SQL NVARCHAR(MAX)

SET @IdentSQL = N'
SELECT 
    DB_ID() AS database_id,
    IC.object_id,
    T.name AS object_name,
    IC.name AS column_name,
    CAST(IC.last_value AS BIGINT) AS last_value,
    RC.row_count,
    IC.system_type_id,
    IC.user_type_id,
    IC.max_length,
    CAST(IC.increment_value AS BIGINT) AS increment_value,
    CAST(IC.seed_value AS BIGINT) AS seed_value,
    S.name AS schema_name
FROM sys.identity_columns IC
INNER JOIN sys.tables T ON IC.object_id = T.object_id
INNER JOIN sys.schemas S ON T.schema_id = S.schema_id
OUTER APPLY (
    SELECT CASE 
        WHEN IC.max_length IS NOT NULL AND IC.last_value IS NOT NULL THEN 
            POWER(2., IC.max_length * 8 - 1) 
        ELSE NULL 
    END AS max_ident,
    CASE 
        WHEN IC.max_length IS NOT NULL THEN POWER(2., IC.max_length * 8) 
        ELSE NULL 
    END AS max_rows,
    CAST(IC.last_value AS BIGINT) AS last_value_big
) calc
OUTER APPLY (
    SELECT SUM(PS.row_count) AS row_count
    FROM sys.dm_db_partition_stats PS
    WHERE PS.object_id = IC.object_id
    AND PS.index_id < 2 -- HEAP/CLUSTERED
) RC
WHERE (
    -- Avoid NULL values and handle potential issues with division
    (calc.last_value_big IS NOT NULL AND calc.max_ident IS NOT NULL AND 
        calc.last_value_big / calc.max_ident * 100 > @IdentityCollectionThreshold) 
    OR 
    (RC.row_count IS NOT NULL AND calc.max_rows IS NOT NULL AND 
        RC.row_count / calc.max_rows * 100 > @IdentityCollectionThreshold)
)
AND IC.max_length < 9
AND IC.last_value IS NOT NULL
ORDER BY object_name;'

CREATE TABLE #ident (
    database_id SMALLINT NOT NULL,
    object_id INT NOT NULL,
    object_name NVARCHAR(128) NULL,
    column_name NVARCHAR(128) NULL,
    last_value BIGINT NULL,
    row_count BIGINT NULL,
    system_type_id TINYINT NOT NULL,
    user_type_id INT NOT NULL,
    max_length SMALLINT NOT NULL,
    increment_value BIGINT NULL,
    seed_value BIGINT NULL,
    schema_name NVARCHAR(128) NULL
);

DECLARE DBs CURSOR FAST_FORWARD READ_ONLY LOCAL FOR
    SELECT D.name
    FROM sys.databases D
    WHERE state = 0
    AND HAS_DBACCESS(D.name) = 1
    AND D.is_in_standby = 0
    AND D.database_id <> 2
    AND DATABASEPROPERTYEX(D.name, 'Updateability') = 'READ_WRITE';

OPEN DBs;

WHILE 1 = 1
BEGIN
    FETCH NEXT FROM DBs INTO @DBName
	PRINT @DBName
    IF @@FETCH_STATUS <> 0 BREAK
    IF HAS_DBACCESS(@DBName) = 1
    BEGIN
        BEGIN TRY
            SET @SQL = N'USE ' + QUOTENAME(@DBName) + ' ' + @IdentSQL
            INSERT INTO #ident (
                database_id,
                object_id,
                object_name,
                column_name,
                last_value,
                row_count,
                system_type_id,
                user_type_id,
                max_length,
                increment_value,
                seed_value,
                schema_name
            )
            EXEC sp_executesql @SQL, N'@IdentityCollectionThreshold INT', @IdentityCollectionThreshold
        END TRY
        BEGIN CATCH
            PRINT 'Fejl opstod i database: ' + @DBName + '. ' + ERROR_MESSAGE()
        END CATCH
    END
END

CLOSE DBs
DEALLOCATE DBs

SELECT 
    database_id,
    object_id,
    object_name,
    column_name,
    last_value,
    row_count,
    system_type_id,
    user_type_id,
    max_length,
    increment_value,
    seed_value,
    schema_name
FROM #ident

DROP TABLE #ident;
`

**Comment by DavidWiseman** [comment]
Hi,

There is something more going on than an empty table with a BIGINT identity.  For example, it isn't possible to reproduce the issue creating a new empty table with BIGINT identity.  e.g.

```sql
CREATE TABLE Test(
ID BIGINT NOT NULL IDENTITY(1,1),
col1 VARCHAR(10)
)
```

The collection query still works with this new table.  The table also isn't returned - The `IS NOT NULL` changes are not required to exclude the table.  A value of NULL is unknown and won't evaluate as being  `> @IdentityCollectionThreshold`.  The changes _seem_ to be unnecessary.  If it fixes the problem it would be good to know why.

Thanks,

David

**Comment by AGlennDa** [comment]
Hi, 
You are right. I should have testet this first. 
And yes, there was something more going on. 
On the database with the problem, NUMERIC_ROUNDABORT was set to TRUE. 
When I set this to FALSE, the original script worked. 

NUMERIC_ROUNDABORT
"Specifies the level of error reporting generated when rounding in an expression causes a loss of precision."

I don't know if you want to do anything about this - I might just set the setting to false, when I have talked with our developers.

**Comment by DavidWiseman** [comment]
Hi,

Thanks for getting back to me.  I can reproduce the issue and I can fix this from my end.  I can either add `SET NUMERIC_ROUNDABORT OFF` to the top of the collection script.  Or I can change the max_rows calculation to `POWER(2E0,IC.max_length*8) AS max_rows` (making it a FLOAT instead of a decimal which would be appropriate for calculating the percent of rows used).

I'll get it fixed in the next update.

Thanks,

David

**Comment by AGlennDa** [comment]
Your work is very much appreciated! Thank you! :)

**Comment by DavidWiseman** [comment]
There is a custom build with the fix [here](https://github.com/DavidWiseman/dba-dash/releases/tag/3.17.1) if you wanted to try it early.  Otherwise it will be included in the next release.

**Comment by PascoBOCC-LeslieBaski** [comment]
With the latest version 3.21.0, I'm still getting the error 
"Microsoft.Data.SqlClient.SqlException (0x80131904): Arithmetic overflow error converting numeric to data type numeric."
I'm unable to change the historical database and turn SET NUMERIC_ROUNDABORT OFF.
I'm a bit new to GitHub so maybe I'm not catching it but which fix was implemented? and is it in version 3.21.0?

**Comment by DavidWiseman** [comment]
@PascoBOCC-LeslieBaski The fix is included in the latest release.  There must be a related bug.  Can you provide the full error details and confirm the Source is still the identity columns collection?

**Comment by PascoBOCC-LeslieBaski** [comment]
this error is from IdentityColumns Collect action:

Microsoft.Data.SqlClient.SqlException (0x80131904): Arithmetic overflow error converting numeric to data type numeric.
Arithmetic overflow error converting numeric to data type numeric.
Arithmetic overflow error converting numeric to data type numeric.
Arithmetic overflow error converting numeric to data type numeric.
Arithmetic overflow error converting numeric to data type numeric.
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at DBADash.DBCollector.GetDataTableAsync(String tableName, String SQL, Int32 commandTimeout, SqlParameter[] param) in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 1363
   at DBADash.DBCollector.GetDataTableAsync(String tableName, String SQL, Int32 commandTimeout, SqlParameter[] param) in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 1365
   at DBADash.DBCollector.AddDataTableAsync(String tableName, String sql, Int32 commandTimeout, SqlParameter[] param) in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 1372
   at DBADash.DBCollector.ExecuteCollectionAsync(CollectionType collectionType) in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 1059
   at DBADash.DBCollector.<>c__DisplayClass76_0.<<CollectAsync>b__0>d.MoveNext() in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 613
--- End of stack trace from previous location ---
   at DBADash.DBCollector.CollectAsync(CollectionType collectionType) in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 610
ClientConnectionId:bc7929b1-54a3-440a-ab7b-73982f7c3234
Error Number:8115,State:1,Class:16

**Comment by PascoBOCC-LeslieBaski** [comment]
I can also confirm all is well, except for one server's set of historical databases that have the setting turned on. 
Here is my little test case:

declare @IdentityCollectionThreshold int = 5;

--select SESSIONPROPERTY('NUMERIC_ROUNDABORT')
SET NUMERIC_ROUNDABORT ON;

with cteDataTypes as (
	SELECT name [sys_name], system_type_id, max_length, precision, scale
	FROM sys.types
	WHERE max_length < 9 --equates to the 3rd Test previously added to prevent arithmatic overflow
	AND max_length > 0 --filtering out strings types
), cteTest1Parts as (
	select *, 0 as [calc_last_value_big]
		,CASE max_length 
				WHEN 1 THEN POWER(2.,max_length*8) 
				ELSE POWER(2.,max_length*8-1)-1 
		END [calc_max_ident] 
	from cteDatatypes
), cteTest1Calc as (
	/*calc.last_value_big / calc.max_ident > @IdentityCollectionThreshold*/
	select *, IIF(calc_last_value_big / calc_max_ident > @IdentityCollectionThreshold, 'True', 'False') [LastValueOverMaxIdent]  
	from cteTest1Parts
), cteTest2Parts as (
	select *, 1 [RC_row_count] -- in my case this value is 1
		, POWER(2E0,max_length*8) [calc_max_rows]
	from cteDataTypes
), cteTest2Calc as (
	/*OR RC.row_count  / calc.max_rows * 100 > @IdentityCollectionThreshold*/
	select *, iif(RC_row_count / calc_max_rows * 100 > @IdentityCollectionThreshold, 'True', 'False') [RowCountOverMaxRowsTest]
	from cteTest2Parts
)
select * 
from cteTest1Calc

**Comment by DavidWiseman** [comment]
@PascoBOCC-LeslieBaski 

I can reproduce the issue - thank you for reporting it.  Can you test this script to confirm the fix?

```sql
DECLARE @IdentityCollectionThreshold INT = 5;
--
SET NOCOUNT ON 
SET TRAN ISOLATION LEVEL READ UNCOMMITTED

DECLARE @DBName SYSNAME
DECLARE @IdentSQL NVARCHAR(MAX)
DECLARE @SQL NVARCHAR(MAX)
SET @IdentSQL = N'SELECT DB_ID() AS database_id,
	IC.object_id,
	T.name AS object_name,
	IC.name AS column_name,
	CAST(IC.last_value AS BIGINT) AS last_value,
	RC.row_count,
	IC.system_type_id,
	IC.user_type_id,
	IC.max_length,
	CAST(IC.increment_value AS BIGINT) AS increment_value,
	CAST(IC.seed_value AS BIGINT) AS seed_value,
	S.name AS schema_name
FROM sys.identity_columns IC
INNER JOIN sys.tables T ON IC.object_id = T.object_id
INNER JOIN sys.schemas S ON T.schema_id = S.schema_id
OUTER APPLY(SELECT	CASE IC.max_length
						WHEN 1 THEN POWER(2.,IC.max_length*8) 
							ELSE POWER(2.,IC.max_length*8-1)-1 
					END AS max_ident,
					POWER(2.,IC.max_length*8) AS max_rows,
					CAST(IC.last_value AS BIGINT) as last_value_big
			) calc
OUTER APPLY(SELECT SUM(PS.row_count) row_count
			FROM sys.dm_db_partition_stats PS
			WHERE PS.object_id = IC.object_id
			AND PS.index_id < 2 -- HEAP/CLUSTERED
			) RC
WHERE (
	/* last_value is more than threshold percent of the max identity value */
	calc.last_value_big / CAST(calc.max_ident AS FLOAT) * 100 > @IdentityCollectionThreshold 
	/* Table row count is more than the threshold percent of the max number of rows (taking negative values into account)  
	   This is useful if identity was started with a negative number or if the identity was reseeded later with a negative number
	*/
	OR RC.row_count  / CAST(calc.max_rows AS FLOAT) * 100 > @IdentityCollectionThreshold 
	)
AND IC.max_length < 9 /* Exclude decimal types that would be larger than BIGINT and break calculations */
ORDER BY object_name;'

CREATE TABLE #ident(
    database_id SMALLINT NOT NULL,
    object_id INT NOT NULL,
    object_name NVARCHAR(128)  NULL,
    column_name NVARCHAR(128) NULL,
    last_value BIGINT NULL,
    row_count BIGINT NULL,
    system_type_id TINYINT NOT NULL,
    user_type_id INT NOT NULL,
    max_length SMALLINT NOT NULL,
    increment_value BIGINT NULL,
    seed_value BIGINT NULL,
	schema_name NVARCHAR(128) NULL
);


DECLARE DBs CURSOR FAST_FORWARD READ_ONLY LOCAL FOR
			SELECT D.name
			FROM sys.databases D
			WHERE state = 0
			AND HAS_DBACCESS(D.name) = 1
			AND D.is_in_standby = 0
			AND D.database_id <> 2
			AND DATABASEPROPERTYEX(D.name, 'Updateability') = 'READ_WRITE';

OPEN DBs;

WHILE 1=1
BEGIN
	FETCH NEXT FROM DBs INTO @DBName
	IF @@FETCH_STATUS<>0
		BREAK
	IF HAS_DBACCESS(@DBName)=1
	BEGIN
		SET @SQL =  N'USE ' + QUOTENAME(@DBName)  + '
		' + @IdentSQL

		INSERT INTO #ident
		(
		    database_id,
		    object_id,
		    object_name,
		    column_name,
		    last_value,
		    row_count,
		    system_type_id,
		    user_type_id,
		    max_length,
		    increment_value,
		    seed_value,
			schema_name
		)
		EXEC sp_executesql @SQL,N'@IdentityCollectionThreshold INT',@IdentityCollectionThreshold
	END
END
CLOSE DBs 
DEALLOCATE DBs

SELECT database_id,
       object_id,
       object_name,
       column_name,
       last_value,
       row_count,
       system_type_id,
       user_type_id,
       max_length,
       increment_value,
       seed_value,
	   schema_name
FROM #ident

DROP TABLE #ident
```

**Comment by PascoBOCC-LeslieBaski** [comment]
That fix, solves it for me. Thank you. And thank you again for this awesome tool.

**Comment by DavidWiseman** [comment]
Thank you for confirming.  The fix will be included in the next release - probably next week.

**Comment by DavidWiseman** [comment]
Fix included in 3.22 🎉
