### ISSUE TITLE
Slow Queries Not Showing in Database Context

### ISSUE THREAD

**Issue by jacobgexigo** [trimble-oss/dba-dash#481]
I can see that the collection is running and there are entries on the grid for the database at the server level, but if you click on the database and go to Slow Queries there is nothing populating.  I'm on the latest version.

![image](https://user-images.githubusercontent.com/29784949/207871155-d5c3aab6-f5cc-46d2-9d11-6a83c49919f0.png)

Server Level:
![image](https://user-images.githubusercontent.com/29784949/207871288-beb81831-729c-4106-8421-63b32dd3e8cf.png)

Database Level: 
![image](https://user-images.githubusercontent.com/29784949/207871450-3c0fd3f6-fdc8-45cb-b0c6-a3b7ecf112a9.png)

**Comment by DavidWiseman** [comment]
Hi, it seems to be working for me.  Are there definitely slow queries associated with the selected database when you see it grouped by database at the server level?  Does the database have a strange name - containing a % character maybe?  The dynamic SQL generated to filter the DB name will either be:
```sql
AND D.name LIKE @DatabaseName
```
or
```sql
AND D.name = @DatabaseName
```
- Depending if the DB name contains a % character.

Some info to assist troubleshooting:

This extended events session can be created to capture the queries ran by the DBA Dash GUI:
```sql
CREATE EVENT SESSION [DBADashGUI] ON SERVER 
ADD EVENT sqlserver.rpc_completed(
    WHERE ([sqlserver].[client_app_name]=N'DBADashGUI')),
ADD EVENT sqlserver.sql_batch_completed(
    ACTION(sqlserver.client_app_name)
    WHERE ([sqlserver].[client_app_name]=N'DBADashGUI'))
WITH (MAX_MEMORY=4096 KB,EVENT_RETENTION_MODE=ALLOW_SINGLE_EVENT_LOSS,MAX_DISPATCH_LATENCY=30 SECONDS,MAX_EVENT_SIZE=0 KB,MEMORY_PARTITION_MODE=NONE,TRACK_CAUSALITY=OFF,STARTUP_STATE=OFF)
```

At the server level, DBA Dash will run a query similar to this- replacing the InstanceIDs and date parameters:
```sql
exec dbo.SlowQueriesSummary_Get @InstanceIDs=N'123',@FromDate='2022-12-15 13:38:18.127',@ToDate='2022-12-15 14:38:18.127',@GroupBy=N'DatabaseName',@Top=20
```
You can find the instance ID in the dbo.Instances table.

At the database level it will alter this query to pass in the @DatabaseName parameter - and change the group by.
```sql
exec dbo.SlowQueriesSummary_Get @InstanceIDs=N'169',@FromDate='2022-12-15 13:38:28.370',@ToDate='2022-12-15 14:38:28.370',@GroupBy=N'object_name',@DatabaseName=N'4Projects_3G_FT_Master',@Top=20
```

If You pass @Debug=1 it will print out the dynamic SQL that gets executed.

Hope this helps.  Let me know if you find anything.

**Comment by jacobgexigo** [comment]
This is what I see when I run the queries and even just look at the raw data:

![image](https://user-images.githubusercontent.com/29784949/207923564-6df71be7-43c9-4992-a663-8324cf52f5de.png)

**Comment by DavidWiseman** [comment]
This should be working for Azure DB.  The extended event captures the database_id.  This is associated with a database on import when the application runs SlowQueries_Upd.

```sql
FROM @SlowQueries SQ
LEFT JOIN dbo.Databases D ON D.database_id = SQ.database_id AND D.InstanceID = @InstanceID AND D.IsActive=1
```

If the databases collection isn't running or if it has issues this would explain why it's not working.  Try running this:

```
SELECT * FROM dbo.Databases WHERE InstanceID = 374
```

For Azure DB there will be a 1:1 mapping of databases to instances.  You should get a single row returned.  Check the IsActive column is 1 if you get a row back.  If you don't get a row, check that the Databases collection is enabled and check to error log to see if there are any issues for this collection.

Note: If you get the Databases collection working, it will only fix new stuff going forward.

Let me know what you find.

**Comment by jacobgexigo** [comment]
Yes, it is active in the Databases table.

![image](https://user-images.githubusercontent.com/29784949/208126121-517a900c-5fe2-417b-9a7b-fddc0d8d641a.png)

**Comment by DavidWiseman** [comment]
That could suggest that the database_id captured by the extended event is different to the one captured in dbo.Databases for that instance.  Usually, queries are limited in Azure to span a single database.  Cross-database queries are possible though so maybe that's an explanation.  I don't think we should be seeing queries from a different DB in an elastic pool - I might be wrong though.

**Comment by jacobgexigo** [comment]
I'm running a mass update to apply the DatabaseID to any record with it NULL that has a concatenated ConnectionID, doing a join between Instances and Databases.  It seems to be working to get the data to show up in the GUI.  Once done I'll see if new entries are still getting a NULL value.  Is it possible anything changed after around 11/15 that could have been missed if we had Persist XE Sessions enabled on all of them (because we had to set the memory lower on them)?

**Comment by jacobgexigo** [comment]
I looked at the live data for the database in Azure and it is 42 (same in the extended events raw data), but in the dbo.Databases table in the DBADash database it shows as Database_Id = 5.  Not sure why that is, but I know that DB_ID() can change in Azure at any time because of the way they migrate databases between hardware.  We've had to deal with that and not use ID now, but name on the instance.

**Comment by DavidWiseman** [comment]
The DatabaseID issue doesn't seem to come up for the AzureDB instances I monitor.  Maybe this issue occurs as the result of elastic/cross database queries.  
For AzureDB the app can probably just drop the @DatabaseName filter as there is a 1:1 mapping between InstanceID and DatabaseID anyway.

**Comment by DavidWiseman** [comment]
Or this suggests it's probably related to failover:

https://dba.stackexchange.com/questions/138809/database-id-for-our-database-in-sys-databases-does-not-match-that-of-db-id-o
https://social.technet.microsoft.com/Forums/en-US/20791489-fad8-4469-98f5-1749d9450949/database-id-gets-changed?forum=ssdsgetstarted

**Comment by DavidWiseman** [comment]
Included in 2.33.0 🎉
